server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rate_limit_db
    username: admin
    password: admin
    # JPA properties
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql